/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LoginPage extends javax.swing.JFrame {
    int attempt =0;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2user = new javax.swing.JTextField();
        jButton1Login = new javax.swing.JButton();
        jButton2Exit = new javax.swing.JButton();
        jButton3Reset = new javax.swing.JButton();
        jLabel4Create = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event Centre Management");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/event2.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 300, 320));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 320, 360));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextField2user.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2user.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jTextField2user.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jTextField2user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

        jButton1Login.setBackground(new java.awt.Color(34, 167, 240));
        jButton1Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Login.setText("Login");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 70, -1));

        jButton2Exit.setBackground(new java.awt.Color(51, 51, 255));
        jButton2Exit.setForeground(new java.awt.Color(255, 255, 255));
        jButton2Exit.setText("Exit");
        jButton2Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ExitActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, -1));

        jButton3Reset.setBackground(new java.awt.Color(192, 57, 43));
        jButton3Reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton3Reset.setText("Reset");
        jButton3Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ResetActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 70, -1));

        jLabel4Create.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4Create.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4Create.setText("Click here to create a new account!");
        jLabel4Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4CreateMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, -1));

        jPasswordField1.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 380, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ExitActionPerformed
        JFrame frame = new JFrame();        
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit" , "Event Management System", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ExitActionPerformed

    private void jButton3ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ResetActionPerformed
        jTextField2user.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton3ResetActionPerformed

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
         String username = jTextField2user.getText();
         String password = jPasswordField1.getText();
         if(username.contains("admin")&& password.contains("123")){
         Homepage_Event hme = new Homepage_Event();
        hme.setVisible(true);
        this.dispose();
         }else if (!(username.contains("admin")&& password.contains("123"))){
             jTextField2user.setText("");
             jPasswordField1.setText("");
             attempt +=1;
             
             if(attempt == 3){
                 System.exit(0);
             }
         }
        
        
    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jLabel4CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4CreateMouseClicked
             userReg rg = new userReg();
              rg.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jLabel4CreateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton2Exit;
    private javax.swing.JButton jButton3Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4Create;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2user;
    // End of variables declaration//GEN-END:variables
}
